routes/web.php
<?php

use App\Http\Controllers\Admin\AdminDashboardController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\ShopController;
use App\Http\Controllers\Site\SiteController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Site Routes
Route::get('/',[SiteController::class,'index'])->name('home');
Route::get('/about',[SiteController::class,'about'])->name('about');
Route::get('/help',[SiteController::class,'help'])->name('help');
Route::get('/business-setup',[SiteController::class,'businessSetup'])->name('business_setup');
Route::get('/shops',[SiteController::class,'shops'])->name('shops');

Route::middleware('guest')->group(function (){
    Route::get('/login',[SiteController::class,'login'])->name('login');
    Route::post('/authenticate',[AuthController::class,'userAuthenticate'])->name('authenticate');
    Route::get('/forgot',[SiteController::class,'forgot'])->name('forgot');
    Route::get('/signup',[SiteController::class,'signup'])->name('signup');
    Route::get('/seller-setup',[SiteController::class,'sellerSignup'])->name('seller_signup');
});

Route::get('/login',function (){
    return view('site.auth.login');
})->middleware('guest')->name('login');

// Admin Routes
Route::prefix('admin')->name('admin.')->group(function (){

    // Admin Guest Middleware Group
    Route::middleware('guest')->group(function (){

        Route::get('/login',[AuthController::class,'adminLogin'])->name('login');
        Route::post('/authenticate',[AuthController::class,'adminAuthenticate'])->name('authenticate');
    });

    // Admin Protected Middleware Group
    Route::middleware(['auth','role:admin'])->group(function (){

        Route::post('/logout',[AuthController::class,'logout'])->name('logout');
        Route::get('/dashboard',[AdminDashboardController::class,'index'])->name('dashboard');

        Route::resource('/users',UserController::class)->only(['index','show','destroy']);
        Route::resource('/shops',ShopController::class)->only(['index','show','destroy']);
        Route::resource('/services',ServiceController::class)->only(['index','show','destroy']);

    });
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use phpDocumentor\Reflection\Types\True_;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'email',
        'password',
        'mobile_number',
        'role_id',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'status' => 'boolean',
    ];

    // one to many relationship with roles where 1 role can have many users and 1 user can have 1 role
    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    public function shop()
    {
        return $this->hasOne(Shop::class);
    }

    public function appointments()
    {
        return $this->hasMany(Appointment::class,'user_id');
    }


    public function hasRole($role)
    {
        return $this->role->name == $role ? true : false;
    }

    public function getFullNameAttribute() {
        return ucfirst($this->first_name) . ' ' . ucfirst($this->last_name);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;

class UserController extends Controller
{
    public function index ()
    {
        $users = User::with(['role','shop'])->paginate(10);
        return view('admin.users.index',['users' => $users]);
    }

    public function show ($id)
    {
        $user = User::where('id',$id)->with(['role','shop'])->first();
        return view('admin.users.show',['user' => $user]);
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.layouts.dashboard')
@section('title','Create New User')
@section('content')
    <div class="nk-block-head nk-block-head-sm">
        <div class="nk-block-between">
            <div class="nk-block-head-content">
                <h3 class="nk-block-title page-title">Add New User</h3>
                <div class="nk-block-des text-soft">
                    <p>You have total 2,595 users.</p>
                </div>
            </div><!-- .nk-block-head-content -->
        </div><!-- .nk-block-between -->
    </div><!-- .nk-block-head -->
    <div class="nk-block">
        <div class="card card-bordered">
            <div class="card-inner">
                @include('admin.partials._show-validation-errors')

                <form action="{{route('admin.users.store')}}" method="POST" class="form-validate">
                    @csrf
                    <div class="row g-4">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label class="form-label" for="first_name">First name</label>
                                <div class="form-control-wrap">
                                    <input type="text" name="first_name" class="form-control form-control-lg" id="first_name" required>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label class="form-label" for="first_name">Last name</label>
                                <div class="form-control-wrap">
                                    <input type="text" name="last_name" class="form-control form-control-lg" id="last_name" required>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label class="form-label" for="email">Email address</label>
                                <div class="form-control-wrap">
                                    <input type="email" name="email" class="form-control form-control-lg" id="email" data-rule-email="true" required>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <div class="form-label-group">
                                    <label class="form-label" for="password">Password</label>
                                </div>
                                <div class="form-control-wrap">
                                    <a href="#" class="form-icon form-icon-right passcode-switch" data-target="password">
                                        <em class="passcode-icon icon-show icon ni ni-eye"></em>
                                        <em class="passcode-icon icon-hide icon ni ni-eye-off"></em>
                                    </a>
                                    <input type="password" name="password" class="form-control form-control-lg" id="password" required>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label class="form-label" for="mobile_number">Mobile No</label>
                                <div class="form-control-wrap">
                                    <input type="text" name="mobile_number" class="form-control form-control-lg" id="mobile_number" required>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label class="form-label" for="role">Select Role</label>
                                <div class="form-control-wrap">
                                    <select class="form-select" name="role" id="role" data-ui="lg" required>
                                        @foreach($roles as $role)
                                            <option value="{{$role->id}}">{{ucfirst($role->name)}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="col-12">
                            <div class="form-group">
                                <button type="submit" class="btn btn-lg btn-primary">Save</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div><!-- .nk-block -->
@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.dashboard')
@section('title','Edit User')
@section('content')
    <div class="nk-block-head nk-block-head-sm">
        <div class="nk-block-between">
            <div class="nk-block-head-content">
                <h3 class="nk-block-title page-title">Edit User</h3>
                <div class="nk-block-des text-soft">
                </div>
            </div><!-- .nk-block-head-content -->
        </div><!-- .nk-block-between -->
    </div><!-- .nk-block-head -->
    <div class="nk-block">
        <div class="card card-bordered">
            <div class="card-inner">
                @include('admin.partials._show-validation-errors')

                <form action="{{route('admin.users.update',$user->id)}}" method="POST">
                    @csrf
                    @method('PATCH')
                    <div class="row g-4">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label class="form-label" for="first_name">First name</label>
                                <div class="form-control-wrap">
                                    <input type="text" name="first_name" class="form-control form-control-lg" id="first_name" value="{{$user->first_name}}" required>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label class="form-label" for="last_name">Last name</label>
                                <div class="form-control-wrap">
                                    <input type="text" name="last_name" class="form-control form-control-lg" id="last_name" value="{{$user->last_name}}" required>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label class="form-label" for="email">Email address</label>
                                <div class="form-control-wrap">
                                    <input type="email" name="email" class="form-control form-control-lg" id="email" value="{{$user->email}}" data-rule-email="true" required>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="form-label" for="mobile_number">Mobile No</label>
                                <div class="form-control-wrap">
                                    <input type="text" name="mobile_number" class="form-control form-control-lg" id="mobile_number" value="{{$user->mobile_number}}" required>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="form-label" for="role">Select Role</label>
                                <div class="form-control-wrap">
                                    <select class="form-select update_role_select" name="role" id="role" data-ui="lg" required>
                                        @foreach($roles as $role)
                                            <option value="{{$role->id}}" {{($user->role_id == $role->id) ? "selected":''}}>{{ucfirst($role->name)}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="col-12">
                            <div class="form-group">
                                <button type="submit" class="btn btn-lg btn-primary">Update</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div><!-- .nk-block -->
@endsection